apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-mapper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-mapper
  template:
    metadata:
      labels:
        app: mqtt-mapper
    spec:
      nodeName: raspberrypi # replace with your edge node name
      containers:
        - name: mqtt-mapper
          volumeMounts: # Required, mapper need to communicate with grpcclient and get the config
            - name: test-volume
              mountPath: /etc/kubeedge
            - name: config
              mountPath: /tmp
          image: ryusid/mqtt-mapper:arm64v3 # Replace with your mapper image name
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          command: [ "/app/coap"]
          args:
            - "--v 5"
      volumes:
        - name: test-volume
          hostPath:
            path: /etc/kubeedge
            type: Directory
        - name: config
          configMap:
            name: cm-mapper
            items:
              - key: configData
                path: config.yaml
