apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: coap-sensor-room1
  namespace: default
  labels:
    description: 'Motion-Detection-Camera'
    manufacturer: 'Custom'
    model: 'motion-sensor-v1'
spec:
  deviceModelRef:
    name: coap-sensor-model
  nodeName: raspberrypi
  properties:
    - name: motion
      collectCycle: 15000
      reportCycle: 15000
      reportToCloud: true
      visitors:
        protocolName: coap
        configData:
          dataType: bool
          propertyName: motion
    - name: last_detection
      collectCycle: 15000
      reportCycle: 15000
      reportToCloud: true
      visitors:
        protocolName: coap
        configData:
          dataType: string
          propertyName: last_detection
    - name: class
      collectCycle: 15000
      reportCycle: 15000
      reportToCloud: true
      visitors:
        protocolName: coap
        configData:
          dataType: string
          propertyName: class

  protocol:
    protocolName: coap
    configData:
      addr:  "192.168.8.222:5683"  # Replace XXX with camera's actual IP
      motionPath: "/motion"
      lastPath: "/lastdetection"
      classPath: "/class"
      observeMotion: true
      observeLast: true
      observeClass: true
      timeout: "5s"
