apiVersion: devices.kubeedge.io/v1beta1
kind: DeviceModel
metadata:
  name: mqtt-sensor-model
  namespace: default
spec:
  properties:
    - name: motion
      description: Boolean motion state
      type: BOOLEAN
      accessMode: ReadOnly
    - name: last_detection
      description: Timestamp of latest detected motion (ISO8601)
      type: STRING
      accessMode: ReadOnly
    - name: class
      description: Classification label (e.g., person, unknown)
      type: STRING
      accessMode: ReadOnly
  protocol: mqtt
