apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: motioncam-coap
  namespace: default
  labels:
    description: 'Motion-Detection-Camera'
    manufacturer: 'Custom'
    model: 'motion-sensor-v1'
spec:
  deviceModelRef:
    name: coap-motion-model
  nodeName: raspberrypi
  properties:
    - name: motion
      collectCycle: 15000
      reportCycle: 15000
      reportToCloud: true
      visitors:
        protocolName: coap
        configData:
          dataType: string
          propertyName: motion
  protocol:
    protocolName: coap
    configData:
      addr:  "192.168.8.222:5683"  # Replace XXX with camera's actual IP
      path: "/motion"
      observe: true
      timeout: "5s"
status:
  twins:
    - propertyName: motion
      reported:
        value: ""
        metadata:
          type: "string"
