apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: motioncam
  namespace: default
  labels:
    description: 'Motion-Detection-Camera'
    manufacturer: 'Custom'
    model: 'motion-sensor-v1'
spec:
  deviceModelRef:
    name: motion-sensor-model
  nodeName: raspberrypi
  properties:
    - name: motion
      collectCycle: 15000
      reportCycle: 15000
      reportToCloud: true
      visitors:
        protocolName: mqtt
        configData:
          dataType: string
          propertyName: motion
  protocol:
    protocolName: mqtt
    configData:
      brokerURL: tcp://192.168.8.218:1883
      clientID: motion-mapper-motioncam
      motionTopic: motion
      username: ""
      password: ""
      qos: 0
status:
  twins:
    - propertyName: motion
      reported:
        value: ""
        metadata:
          type: "string"