apiVersion: devices.kubeedge.io/v1beta1
kind: DeviceModel
metadata:
  name: motion-sensor-model
  namespace: default
spec:
  properties:
  - name: motion
    description: Motion detection status from MQTT sensor
    type: STRING
    accessMode: ReadOnly
  protocol: mqtt