apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: mqtt-sensor-room1
  namespace: default
spec:
  deviceModelRef:
    name: mqtt-sensor-model
  nodeName: raspberrypi
  properties:
    - name: motion
      collectCycle: 15000
      reportCycle: 15000
      reportToCloud: true
      visitors:
        protocolName: mqtt
        configData:
          dataType: boolean
          propertyName: motion
    - name: last_detection
      collectCycle: 15000
      reportCycle: 15000
      reportToCloud: true
      visitors:
        protocolName: mqtt
        configData:
          dataType: string
          propertyName: last_detection
    - name: class
      collectCycle: 15000
      reportCycle: 15000
      reportToCloud: true
      visitors:
        protocolName: mqtt
        configData:
          dataType: string
          propertyName: class
  protocol:
    protocolName: mqtt
    configData:
      brokerURL: tcp://192.168.8.218:1883
      clientID: motion-mapper-mqtt-sensor-room1
      qos: 0
      # Per-prop topics your mapper subscribes to:
      motionTopic:        motion/device/mqtt-sensor-room1/state        # payload: "true"/"false"
      lastDetectionTopic: motion/device/mqtt-sensor-room1/last_detection # payload: "2025-08-11T12:34:56Z"
      classTopic:         motion/device/mqtt-sensor-room1/class         # payload: "person"/"unknown"
      # Optional if you test images over MQTT (see ยง4):
      imageTopic:         motion/device/mqtt-sensor-room1/image
status:
  twins:
    - propertyName: motion
      reported:
        value: ""
        metadata:
          type: "bool"
    - propertyName: class
      reported:
        value: ""
        metadata:
          type: "string"
    - propertyName: last_detection
      reported:
        value: ""
        metadata:
          type: "string"

