apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-grpc-classifier
  namespace: default
spec:
  replicas: 1
  selector: { matchLabels: { app: edge-classifier } }
  template:
    metadata: { labels: { app: edge-classifier } }
    spec:
      nodeSelector: { kubernetes.io/hostname: raspberrypi } # Change with the appropriate node name
      hostNetwork: true                      # expose CoAP on the edge host IP
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: classifier
        image: ryusid/grpc-worker:latest
        env:
        - { name: CLASS_NAMES, value: "edge1,edge2,edge3,edge4,edge5" }
        - { name: GRPC_LOGGER, value: "Edge-GRPC" }
        - { name: GRPC_BIND, value: "0.0.0.0:50051" }
        - { name: INFER_DELAY_MS, value: "10" }
